# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "playbook.yml"
    ansible.become = "true"
  end


  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "server" do |ns01|
    ns01.vm.network "private_network", ip: "192.168.50.10"
    ns01.vm.hostname = "server"
  end

  config.vm.define "client" do |ns02|
    ns02.vm.network "private_network", ip: "192.168.50.11"
    ns02.vm.hostname = "client"
  end
end
