# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :"ipa.example.com" => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
        :playbook => 'server.yml'
  },
  :"ipa-client.example.com" => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.102',
    :playbook => 'client.yml'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          if boxname == "ipa.example.com"
            box.vm.network "forwarded_port", guest: 443, host: 4443
            box.vm.network "forwarded_port", guest: 389, host: 13389
          end
          # box.vm.provision :hosts do |provisioner|
        	#   provisioner.add_host boxconfig[:ip_addr], [boxname.to_s]
          # end
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

          # box.vm.provision :shell do |s|
          #    s.inline = 'mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh'
          # end

          box.vm.synced_folder ".", "/home/vagrant/ipa_lab"
          # box.vm.provision "ansible" do |ansible|
          #   ansible.playbook = boxconfig[:playbook]
          # end
      end
  end
end
