---
- hosts: all
  become: yes
  vars:
    vm_swappiness: 1
    vm_dirty_background_ratio: 5
    fs_file_max: 2097152
    net_core_somaxconn: 65535
    net_core_netdev_max_backlog: 262144
    net_core_optmem_max: 25165824
    net_core_rmem_default: 31457280
    net_core_rmem_max: 67108864
    net_core_wmem_default: 31457280
    net_core_wmem_max: 67108864
    net_ipv4_tcp_syncookies: 1
    net_ipv4_conf_all_rp_filter: 1
    net_ipv4_icmp_echo_ignore_broadcasts: 1
    net_ipv4_conf_all_log_martians: 1
    net_ipv4_conf_all_accept_source_route: 0
    net_ipv4_conf_all_accept_redirects: 0
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (yum -y update && yum install -y python-minimal)

    - name: Install epel-release package
      yum:
        name: epel-release
        state: latest
        update_cache: yes

    - name: check for updates (yum)
      yum: list=updates update_cache=true

    - name: Setup necessary packages
      yum: name="{{ item }}" state=latest update_cache=yes
      with_items:
        - net-tools
        - bind-utils
        - wget
        - curl
        - telnet
        - mailx
        - vim
        - nmap
        - traceroute
        - w3m
        - htop
        - iftop
        - policycoreutils-python
        - atop
        - iotop
        - lsof
        - mtr

    - name: 'Copy sysctl.conf file'
      template:
        src: "sysctl.conf.j2"
        dest: "/etc/sysctl.conf"
        force: yes

    - name: 'Reload sysctl'
      shell: sysctl --system
