# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :client => {
        :box_name => "centos/7",
        :ip_addr => '192.168.12.50'
  },
  :server => {
        :box_name => "centos/7",
        :ip_addr => '192.168.12.51'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end



          # box.vm.provision :shell do |s|
          #    s.inline = 'mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh'
          # end
          box.vm.synced_folder ".", "/home/vagrant/backup_lab"
      end
  end
end
