---
download_url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
download_folder: /opt
java_version_path: jdk1.8.0_131
java_version_path_short: jdk-8u131
java_name: "{{download_folder}}/{{java_version_path}}"
java_archive: "{{download_folder}}/{{java_version_path_short}}-linux-x64.tar.gz"
nginx_conf_name: kibana
nginx_config_path: /etc/nginx
