---
- include_tasks: roles/base_install.yml
- name: 'install dependencies'
  yum: name="{{ item }}" state=latest update_cache=yes
  with_items:
    - 'nginx'

- name: 'Enable nginx'
  shell: systemctl enable nginx

- name: Add http service
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Add https service
  firewalld:
    service: https
    permanent: true
    state: enabled

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted

- name: Add remote syslog config
  lineinfile:
    path: /etc/rsyslog.conf
    line: "*.* @{{ log_ip }}:514"
  notify:
    - restart rsyslog

- name: 'Copy application nginx {{ nginx_conf_name }} config'
  template:
    src: "templates/{{ nginx_conf_name }}.j2"
    dest: "{{ nginx_config_path }}/conf.d/{{ nginx_conf_name }}.conf"
    force: yes
  notify:
    - restart nginx

- name: Install filebeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.4.2-x86_64.rpm
    state: latest

- name: 'Copy filebeat config'
  template:
    src: templates/filebeat.j2
    dest: /etc/filebeat/filebeat.yml
    force: yes

- name: Restart filebeat
  service:
    name: filebeat
    state: restarted
