---
- name: Configure log
  hosts: log
  become: True
  roles:
    - log

- name: Configure web
  hosts: web
  become: True
  gather_facts: no
  roles:
    - web

- name: Configure elk
  hosts: elk
  become: True
  gather_facts: no
  roles:
    - elk
