---
- name: install python 2
  raw: test -e /usr/bin/python || (yum -y update && yum install -y python-minimal)

- name: Update all packages to the latest version
  yum:
    name: '*'
    state: latest

- name: 'Install epel-release'
  yum: name=epel-release state=latest
