---
- name: 'Logstash: Copy logstash.repo file'
  copy:
    src: "{{ role_path }}/files/logstash.repo"
    dest: /etc/yum.repos.d/logstash.repo

- name: 'Logstash: Install logstash'
  yum:
    name: https://artifacts.elastic.co/downloads/logstash/logstash-6.2.4.rpm
    state: present

- name: 'Logstash: allow 5400 for selinux'
  seport:
      ports: 5400
      proto: tcp
      setype: http_port_t
      state: present

- name: 'Logstash: Copy logstash read pattern'
  copy:
    src: "{{ role_path }}/files/logstash-nginx.conf"
    dest: /etc/logstash/conf.d/logstash-nginx.conf

- name: 'Logstash: Restart logstash'
  service:
    name: logstash
    state: restarted
