# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "playbook.yml"
    ansible.become = "true"
  end


  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
    v.cpus = 1
  end

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.50.10"
    master.vm.hostname = "master"
  end

  config.vm.define "slave" do |slave|
    slave.vm.network "private_network", ip: "192.168.50.11"
    slave.vm.hostname = "slave"
  end

  config.vm.define "barman" do |slave|
    slave.vm.network "private_network", ip: "192.168.50.12"
    slave.vm.hostname = "barman"
  end
end
